version: '3.9'

services:
    api:
      image: "localhost:7002/api:${IMAGE_TAG}"
      build: .
      container_name: "${API_CONT_NAME}"
      environment:
        - Postgres=Server=postgresql_database;Port=5432;Database=${MAIN_DB_NAME};User Id=admin;Password=riv4lz5683;
        - AuthConnection=Server=auth_db;Port=5432;Database=${AUTH_DB_NAME};User Id=admin;Password=riv4lz5683;
        - ChatConnection=Server=chat_db;Port=5432;Database=${CHAT_DB_NAME};User Id=admin;Password=riv4lz5683;
      ports:
        - "${API_PORT}:80" 
      depends_on:
        - redis
        - postgresql_database
        - auth_db
        - chat_db


    redis:
      image: redis:latest
      container_name: "${REDIS_CONT_NAME}"
      ports:
        - ${REDIS_PORT}:6379
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis-data:/data
      depends_on:
        - postgresql_database

    
    redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: "${REDIS_CMD_CONT_NAME}"
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=root
        - HTTP_PASSWORD=secret
      ports:
        - ${REDIS_CMD_PORT}:8081
      depends_on:
        - redis


    postgresql_database:
      image: postgres:latest
      container_name: "${MAIN_DB_CONT_NAME}"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=${MAIN_DB_NAME}
        
      ports: 
        - ${MAIN_DB_PORT}:5432
      restart: always
      volumes:
        - postgres-data:/var/lib/postgresql/data


    auth_db:
      image: postgres:latest
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=${AUTH_DB_NAME}
        
      ports: 
        - ${AUTH_DB_PORT}:5432
      restart: always
      volumes:
        - auth-data:/var/lib/auth/postgres/data

    chat_db:
      image: postgres:latest
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=${CHAT_DB_NAME}
        
      ports: 
        - ${CHAT_DB_PORT}:5432
      restart: always
      volumes:
        - chat-data:/var/lib/chat/postgres/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: "${DB_ADMIN_CONT_NAME}"
      environment: 
        - PGADMIN_DEFAULT_EMAIL=jbuus9@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=riv4lz5683
      ports:
        - ${DB_ADM_PORT}:80
      restart: always
      volumes:
        - pgadmin-data:/var/lib/pgadmin


volumes:
  redis-data:
  postgres-data:
  pgadmin-data:
  auth-data:
  chat-data:

    