version: '3.9'

services:
    api:
      build: .
      image: jonasbf/riv4lz:api-${BUILD_NUMBER}
      container_name: "${API_CONT_NAME}"
      ports:
        - "${API_PORT}:80" 
      depends_on:
        - redis
        - postgresql_database
    redis:
      image: jonasbf/riv4lz:redis-${BUILD_NUMBER}
      container_name: "${REDIS_CONT_NAME}"
      ports:
        - ${REDIS_PORT}:6379
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis-data:/data
      depends_on:
        - postgresql_database
    
    redis-commander:
      image: jonasbf/riv4lz:redis-commander-${BUILD_NUMBER}
      container_name: "${REDIS_CMD_CONT_NAME}"
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=root
        - HTTP_PASSWORD=secret
      ports:
        - ${REDIS_CMD_PORT}:8081
      depends_on:
        - redis

    postgresql_database:
      image: jonasbf/riv4lz:db-${BUILD_NUMBER}
      container_name: "${DB_CONT_NAME}"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=riv4lzMainDb
      ports: 
        - ${DB_PORT}:5432
      restart: always
      volumes:
        - postgres-data:/var/lib/postgresql/data
        
    pgadmin:
      image: jonasbf/riv4lz:db-admin-${BUILD_NUMBER}
      container_name: "${DB_ADMIN_CONT_NAME}"
      environment: 
        - PGADMIN_DEFAULT_EMAIL=jbuus9@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=riv4lz5683
      ports:
        - ${DB_ADM_PORT}:80
      restart: always
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  redis-data:
  postgres-data:
  pgadmin-data:
    
    