version: '3.9'

services:
    api:
      build: .
      container_name: "riv4lz-api-container"
      ports:
        - "5000:80" 
      depends_on:
        - redis
        - postgresql_database

    redis:
      image: redis:latest
      container_name: "redis-container"
      ports:
        - 6379:6379
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis-data:/data
      depends_on:
        - postgresql_database
    
    redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: "redis-commander-container"
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=root
        - HTTP_PASSWORD=secret
      ports:
        - 8888:8081
      depends_on:
        - redis

    postgresql_database:
      image: postgres:latest
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=riv4lzMainDb
      ports: 
        - 5432:5432
      restart: always
      volumes:
        - postgres-data:/var/lib/postgresql/data

    auth_db:
      image: postgres:latest
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=authDb
      ports: 
        - 5433:5432
      restart: always
      volumes:
        - auth-data:/var/lib/auth/postgres/data

    chat_db:
      image: postgres:latest
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=riv4lz5683
        - POSTGRES_DB=chatDb
      ports: 
        - 5434:5432
      restart: always
      volumes:
        - chat-data:/var/lib/chat/postgres/data
        
    pgadmin:
      image: dpage/pgadmin4
      environment: 
        - PGADMIN_DEFAULT_EMAIL=jbuus9@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=riv4lz5683
      ports:
        - 5050:80
      restart: always
      volumes:
        - pgadmin-data:/var/lib/pgadmin    
volumes:
  redis-data:
  postgres-data:
  auth-data:
  pgadmin-data:
  chat-data:
    
    